### ISSUE TITLE
DOMException when switching color

### ISSUE THREAD

**Issue by FannyDemey** [googlecodelabs/candle-bluetooth#1]
Hi 
I first used the project with version 46 of Chrome OS. I was able to select one color, and one effect, and then I had this error "DOMException: GATT operation already in progress". 
Then I updated to this version of Chrome : Version 48.0.2564.8 dev (64-bit)
Now it works perfectly. I can change the color as much as i want to and it's more fluid.

Fanny

**Comment by beaufortfrancois** [comment]
Yes, this is a known issue that has been solved in Bluez, Official Linux Bluetooth protocol stack.
See https://code.google.com/p/chromium/issues/detail?id=531536
