### ISSUE TITLE
Yet another "how to get this working" ticket

### ISSUE THREAD

**Issue by MrCsabaToth** [googlecodelabs/candle-bluetooth#10]
I either can use my Nougat phone's Chrome or Chrome Dev, or my Linux 16.10 Chrome.
The `navigator.bluetooth` is a big `undefined`. I cannot seem to enable this with the `chrome://flags/#enable-web-bluetooth` suggested in another ticket...
Now what?

**Comment by MrCsabaToth** [comment]
I see that the `Origin Trials` were updated in January, maybe it needs to be updated again?

**Comment by MrCsabaToth** [comment]
Got the desktop Chrome working with the `chrome://flags/#enable-experimental-web-platform-features`. After that I don't see the `chrome://flags/#enable-web-bluetooth`, but it works. It's cumbersome on Android though. I wanted my audience to easily engage with my bluetooth bulb.

**Comment by MrCsabaToth** [comment]
The `gatt,connect()` is successful, but any other call results in just pending promises. I'm using a PLAYBULB candle to make my job easier.

**Comment by beaufortfrancois** [comment]
In https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web#before_we_start,

> On Linux, you still have to go to _chrome://flags/#enable-experimental-web-platform-features_, enable the highlighted flag, and restart Chrome for now.

Regarding pending promises, I sadly can't reproduce it ;(
@MrCsabaToth Do you mind sharing logs and file a bug at https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EBluetooth?
See https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs for how to gather these logs.

**Comment by MrCsabaToth** [comment]
I tried it on Windows 10 as well, with non dev (but evergreen) Chrome, v57.x I believe. I had to also perform `chrome://flags/#enable-experimental-web-platform-features`. And for safety I always do `chrome://flags/#enable-web-bluetooth` as well. After that I haven't got to the point that the pairing dialog would pop up. Same thing with Android Beta Chrome and regular Chrome with the lab demo app: didn't get to bluetooth pairing dialog. What saved my ass (I gonna present on this today) before 2 am is sandro-k's Polymer port on Android Chrome. That one triggered an extra popup: enabling location for Chrome (I'm not sure why this is needed). After enabling that though finally I got to the Pairing dialog and that's the only combination which works now. Boy I thought this gonna be an easy demo......

**Comment by beaufortfrancois** [comment]
Windows is not yet fully supported.
It works great on Android, Mac, Chrome OS and Linux*.
See https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#chrome

Please file a bug so that I can help you with some logs.

**Comment by MrCsabaToth** [comment]
Will you'll be at Google I/O or the global GDG Summit? We can meet in person. I think there's a security barrier, that extra privilege dialog (about browser location (?)) what the Polymer version managed to bring up and then that removed the barrier and the demo worked. Otherwise it's very hard to report anything because there are no error messages, just the pairing dialog doesn't show up.

**Comment by beaufortfrancois** [comment]
I'll be at Google I/O.
Let's talk there ;)

**Comment by MrCsabaToth** [comment]
@beaufortfrancois Pick date and time. (preferably in the conference area, or I'll stay at the Country Inn & Suites By Carlson)

**Comment by MrCsabaToth** [comment]
My gmail is first_name.last_name.us@gmail
