### ISSUE TITLE
Guide for android

### ISSUE THREAD

**Issue by vision89** [googlecodelabs/candle-bluetooth#2]
I'm trying to follow along this codelab using my nexus 6 instead of a chromebook but I'm having no luck.  I believe it has something to do with port forwarding to 51792.  When I set it up it shows up red in chrome://inspect/#devices.  I'm not sure where I'm going wrong with it or if there's a bug.  Could the codelab provide better detail for us following along using an android device?

**Comment by vision89** [comment]
I think I see the problem.  Looking further into the android debugging guide I see this:

"In the Host field, enter the IP address (or hostname) and port number where your web application is running. 
This address can be any local location accessible from your development machine. Currently, port numbers must be between 1024 and 32767 (inclusive)."

It looks like my 51792 port is far too high, and it seems to be what chrome dev editor uses by default.  I'm not sure how to change the dev editor to a different port but that should be mentioned somewhere if android is listed as a possibility to use for this codelab.

**Comment by vision89** [comment]
Okay I got it working using python's simpleHTTPServer, I would certainly recommend mentioning a fix for that in the codelab.

**Comment by beaufortfrancois** [comment]
Thank you Dustin! I will definitely update the codelab tomorrow.

**Comment by beaufortfrancois** [comment]
I've just submitted a PR at https://github.com/GoogleChrome/chromedeveditor/pull/4022 to fix the Chrome Dev Editor default port. Let's see how it goes.

**Comment by vision89** [comment]
Okay, thanks Francois
