### ISSUE TITLE
Android not connecting

### ISSUE THREAD

**Issue by vision89** [googlecodelabs/candle-bluetooth#3]
Okay getting closer.  I'm running this using pythons SimpleHTTPServer and using the chrome dev editor on android.  I'm at step 3 just before the Mandatory Bonus section.  When I try to connect I throw a "DOMException: Bluetooth adapter not available." error, when it attempts to call navigator.bluetooth.requestDevice.  I have the playbulb turned on and I have bluetooth turned on in my phone.  I can confirm the device is visible because when I go to the playbulb app I can see it.  I have the enable bluetooth experimental flag enabled.  I'm using the Nexus 6.  I'm not sure if this could be related to the https security requirement?  Just reaching for straws there.  Anyways, I'm not sure if this codelab was tested on the Nexus 6 but I'll be happy to help how I can, if you can offer any advice please let me know!

**Comment by beaufortfrancois** [comment]
Just to be sure, are you running Android 6 (Marshmallow) on your Nexus 6?
Do you see this with [Chrome Dev for Android app](https://play.google.com/store/apps/details?id=com.chrome.dev)?

**Comment by vision89** [comment]
No I'm still on lollipop 5.1.1, I guess the update hasn't gotten to me yet
:-(  Did you include a picture in this email?  If so I can't see it.

On Mon, Nov 30, 2015 at 1:32 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
As stated in the [codelab](https://www.code-labs.io/codelabs/candle-bluetooth/#0), you need a Chromebook _or_ an Android M Device with Chrome Dev Android App and a USB micro to USB cable.

There is a way though to get it to work with Android Lollipop:
See https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md:
- Tip of tree Chromium builds work on Android 5, Lollipop or later for ease of developers - but Chrome versions will only ever support Marshmallow or later.

This means you can get a recent chromium build for Android at https://download-chromium.appspot.com/?platform=Android&type=snapshots and install it to get the Web Bluetooth API working.

**Comment by vision89** [comment]
I see, I think I'll just wait until they roll marshmallow out to me, it
sounds like it shouldn't be too long.  Thanks for the help.

On Mon, Nov 30, 2015 at 6:26 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
For info, installing a chromium build is really easy.
- Just go to  https://download-chromium.appspot.com/?platform=Android&type=snapshots
- Click button to download zip file
- Extract it
- Install ChromePublic.apk
- Bim, you're done ;)

**Comment by vision89** [comment]
Okay I'll install it and have another go at the code-lab as soon as I can.
I have to travel for work this week so if I don't get to it tonight it will
be a few days, but it's on my list :-)

On Mon, Nov 30, 2015 at 6:38 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
No problem ;)

**Comment by beaufortfrancois** [comment]
Please re-open if you're still facing the issue
