### ISSUE TITLE
"no effect" does not reset the "candle effect"

### ISSUE THREAD

**Issue by kdzwinel** [googlecodelabs/candle-bluetooth#4]
Switching from "candle effect" to "no effect" does not stop the flickering. Switching from "flashing" to "no effect" does.

**Comment by beaufortfrancois** [comment]
Thanks Konrad. I'll take a look!

**Comment by beaufortfrancois** [comment]
I've fixed this issue in https://github.com/WebBluetoothCG/demos/pull/38.
In order to keep the codelab "simpler", I won't merge this patch. https://webbluetoothcg.github.io/demos/playbulb-candle/ is the way to go for now.
