### ISSUE TITLE
Does not remove 'connecting' class in arrow function re-write

### ISSUE THREAD

**Issue by rjenks** [googlecodelabs/candle-bluetooth#5]
In section 3 - 'Discovering a nearby candle'.

At the bottom of the section the user is supposed to re-write the app.js code using an arrow function.  The problem is that it's missing a line of code from the original change (near the top of this section).  It's missing the line of code that removes the 'connecting' class.

**Comment by rjenks** [comment]
Same issue in step 4.  Maybe removing the 'connecting' class is not necessary??

**Comment by beaufortfrancois** [comment]
Thank you really much Robert!
I've fixed these issues in the codelab.

Keep up the good work by the way!
