### ISSUE TITLE
Setup Origin Trial for working demo

### ISSUE THREAD

**Issue by sandro-k** [googlecodelabs/candle-bluetooth#7]
As stated in the subject, it would be nice to make the working demo an [Origin Trial](https://docs.google.com/forms/d/e/1FAIpQLSfO0_ptFl8r8G0UFhT0xhV17eabG-erUWBDiKSRDTqEZ_9ULQ/viewform?entry.631548922&entry.1000000&entry.1000001&entry.1999497328=Web+Bluetooth+%28Experimenting+until+late+January+2017%29&entry.1000005). 

I am giving a talk at the [DevFestHH](https://hamburg.devfest.de/schedule/) on Saturday and it would be nice to let people connect to the candle without enabling a flag in chrome. I can prepare the PR for that if needed.

**Comment by sandro-k** [comment]
Sorry was using Chrome 53 on Android. Origin Trail is already active.

**Comment by sandro-k** [comment]
On Chrome Canray I am getting the following error 

```
playbulbCandle.js:22 Uncaught TypeError: Cannot read property 'requestDevice' of undefined
    at PlaybulbCandle.connect (playbulbCandle.js:22)
    at HTMLButtonElement.document.querySelector.addEventListener.event (app.js:3)
```

I suspect that the `Origin Trial token` has expired

**Comment by beaufortfrancois** [comment]
Both codelabs https://googlecodelabs.github.io/candle-bluetooth/ and https://googlecodelabs.github.io/polymer-bluetooth/ have been updated to include a valid origin trial token.
Thanks for the warning!

**Comment by beaufortfrancois** [comment]
Please let me know how goes your talk Sandro!

**Comment by sandro-k** [comment]
Works like a charm 👍  

_offtopic -I have rewritten the the candle example using polymer and will push it to my github this week_

**Comment by beaufortfrancois** [comment]
Wooo! Would love to see this ;)

**Comment by sandro-k** [comment]
Preview is online.. https://sandro-k.github.io/playbulb-polymer/app/

**Comment by beaufortfrancois** [comment]
Yeah! Nice ;)

I see `Battery: NaN%`. Is that expected?

**Comment by sandro-k** [comment]
Nope.. Chome Version 53.0.2785.143 (64-bit) has no issue. Battery is NaN as long as no data is read from the device

**Comment by beaufortfrancois** [comment]
I get 3 errors in Chrome OS 55.0.2883.7 (Official Build) dev (64-bit):

```
sandro-k.github.io/:1 Uncaught (in promise) DOMException: Connection failed for unknown reason.
sandro-k.github.io/:1 Uncaught (in promise) DOMException: Connection failed for unknown reason.
sandro-k.github.io/:1 Uncaught (in promise) DOMException: Connection failed for unknown reason.
```

**Comment by beaufortfrancois** [comment]
Can you try 2.1.2 version of <platinum-bluetooth>?
https://github.com/sandro-k/playbulb-polymer/blob/master/bower.json#L19

**Comment by sandro-k** [comment]
Sure thanks for looking into this.. I will be working on this for the next two days and probably a bit at the Polymer Summit, but need to finish my slides first.

**Comment by beaufortfrancois** [comment]
OK... I've found the issue. Please update your code to avoid parallel `readValue` operations on platform that don't know how to deal with this.

@g-ortuno is this expected?

``` diff
diff --git a/app/elements/playbulb-element.js b/app/elements/playbulb-element.js
index dc0db3a..6cd173c 100644
--- a/app/elements/playbulb-element.js
+++ b/app/elements/playbulb-element.js
@@ -73,12 +73,12 @@
      *
      */
     connect: function () {
-      this.$.bluetoothDevice.request().then(() => {
-        this.$.colorCharacteristic.read().then(this._updateColor)
-        this.$.effectCharacteristic.read()
-        this.$.nameCharacteristic.read()
-        return this.$.batteryCharacteristic.startNotifications()
-      })
+      this.$.bluetoothDevice.request()
+      .then(_ => this.$.colorCharacteristic.read())
+      .then(_ => this._updateColor())
+      .then(_ => this.$.effectCharacteristic.read())
+      .then(_ => this.$.nameCharacteristic.read())
+      .then(_ => this.$.batteryCharacteristic.startNotifications());
     },

```

**Comment by sandro-k** [comment]
Thanks.. I already suspected that reading values in parallel could be the issue. It should not matter how  writes occur. On Android Chrome Dev even crashes..

**Comment by beaufortfrancois** [comment]
Oh really ;( That's bad.
Please can you file an issue at https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EBluetooth?

**Comment by g-ortuno** [comment]
Just to make sure I'm not missing something here: Are the connection errors due to the parallel reads?

**Comment by sandro-k** [comment]
Yes this is what it looks like. I will fix this later today.

**Comment by beaufortfrancois** [comment]
I've found the root issue and filed a bug at https://bugs.chromium.org/p/chromium/issues/detail?id=655931.
In the mean time, @sandro-k I recommend you update to v2.1.2 of platinum-bluetooth elements and update your code as in https://github.com/googlecodelabs/candle-bluetooth/issues/7#issuecomment-253536601

**Comment by sandro-k** [comment]
Thanks @beaufortfrancois, updated everything and it is working like a charm. Changes are live at the gh-page.

**Comment by beaufortfrancois** [comment]
https://sandro-k.github.io/playbulb-polymer/app/bower_components/platinum-bluetooth/bower.json is still 2.1.1. Make sure you run `bower install` and push these changes to your `gh-pages` branch ;)

**Comment by sandro-k** [comment]
Updated.. `bower-install` somehow ended up installing `2.1.1` even when running `bower install --save PolymerElements/platinum-bluetooth#2.1.2`

**Comment by beaufortfrancois** [comment]
Weird! I now see 2.1.2 in https://sandro-k.github.io/playbulb-polymer/app/bower_components/platinum-bluetooth/bower.json 

Good luck for your talk tomorrow!
And please share with me your feedback.

If you need any help (slides review, questions) by the way, feel free to ping me.
