### ISSUE TITLE
Your demo doesn't work

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlecodelabs/candle-bluetooth#9]
Hello,
I am trying out your demo at https://googlecodelabs.github.io/candle-bluetooth/.
The webpage produces the following error:
> playbulbCandle.js:21 Uncaught TypeError: Cannot read property 'requestDevice' of undefined
    at PlaybulbCandle.connect (playbulbCandle.js:21)
    at HTMLButtonElement.document.querySelector.addEventListener.event (app.js:3)
connect @ playbulbCandle.js:21
document.querySelector.addEventListener.event @ app.js:3

I have an active Playbulb candle that I can control just fine with my Android phone.  Why doesn't your webpage connect to it successfully?

Please advise,
Igor

**Comment by IgorGanapolsky** [comment]
I was able to solve this problem by enabling bluetooth protocol in Chrome as described here https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web:

`chrome://flags/#enable-web-bluetooth`

**Comment by beaufortfrancois** [comment]
For the record, I've just updated Origin Trials token so that you don't need to enable the flag until 2017-01-24. See https://github.com/googlecodelabs/candle-bluetooth/commit/cd5ed2f7d5bad63a3b179fb22d9afa578eadc5ba

**Comment by IgorGanapolsky** [comment]
Is it related to https://jpchase.github.io/OriginTrials/?  I am not familiar with origin-trial, nor the string you changed in that token.  Can you please elaborate a bit?

Thanks,
Igor

**Comment by IgorGanapolsky** [comment]
One last quesion.  It says here https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web#available_for_origin_trials:
> As a security feature, discovering Bluetooth devices with navigator.bluetooth.requestDevice must be triggered by a user gesture such as a touch or a mouse click. We're talking about listening to pointerup, click, and touchend events.

But looking at **playbulbCandle.js**, I do not see such logic?

**Comment by beaufortfrancois** [comment]
The `connect` method of PlaybulbCandle at https://github.com/googlecodelabs/candle-bluetooth/blob/gh-pages/playbulbCandle.js#L18 is called in the `click` event of the connect button at https://github.com/googlecodelabs/candle-bluetooth/blob/gh-pages/app.js#L3

**Comment by MrCsabaToth** [comment]
The demo (this repo's gh-pages) doesn't work now with latest 16.10 Ubuntu's Chrome, and also with latest Nougat Andorid's Chrome and Dev Chrome. What to do?

**Comment by IgorGanapolsky** [comment]
@MrCsabaToth What specific error are you seeing in the JavaScript console?

**Comment by skmsd98** [comment]
Test comment

**Comment by skmsd98** [comment]
I am getting this error while trying to run your demo. Is there anything that I need to add or install to my chrome. My chrome version is 68 and i'm on windows 10.

![capture](https://user-images.githubusercontent.com/22544007/43631179-e53c06ae-971b-11e8-9f64-9c2d827c8d10.PNG)

**Comment by beaufortfrancois** [comment]
Did you enable `chrome://flags/#enable-experimental-web-platform-features` flag?
See https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md

**Comment by skmsd98** [comment]
@beaufortfrancois I enabled it and it worked! I was actually trying to enable `chrome://flags/#enable-web-bluetooth` since someone mentioned it above but couldn't find it. Thank you

**Comment by yukulele** [comment]
Hi, I'm getting this error.

I'm on Ubuntu 20.04 with Chromium 91.0.4472.114
I enabled both `enable-unsafe-webgpu` and `enable-experimental-web-platform-features`
